# Generated by Django 4.0.3 on 2022-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Fimler'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kişi', 'verbose_name_plural': 'Kişiler'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.CharField(max_length=3000, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='person',
            name='duty_type',
            field=models.CharField(choices=[('1', 'Görevli'), ('2', 'Oyuncu'), ('3', 'Yönetmen'), ('4', 'Senarist')], max_length=1, verbose_name='görev'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, verbose_name='cinsiyet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Özet'),
        ),
    ]
