# Generated by Django 4.0.3 on 2022-04-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.CharField(max_length=3000, verbose_name='Biyografi'),
        ),
    ]
