# Generated by Django 4.0.3 on 2022-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
