# Generated by Django 4.0.3 on 2022-05-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='is_active',
        ),
    ]
