# Generated by Django 4.0.3 on 2022-05-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
